title: 'Loïc Sapone'
baseline: 'Développeur web'
baseurl: 'https://localhost:8000/'
description: 'Loïc Sapone, développeur web basé à Grenoble - associé chez Mezcalito, compétant en backend et devops'
author: 'Loïc Sapone'
social:
    twitter:
        site: 'LoicSapone'
language: fr
languages:
    -   code: fr
        name: Français
        locale: fr_FR
image: og.png
