title: 'Loïc Sapone'
baseline: 'Senior web developer'
baseurl: 'https://localhost:8000/'
description: 'Loïc Sapone, web developer based in Grenoble - partner at Mezcalito, skilled in backend and devops.'
author: 'Loïc Sapone'
social:
    twitter:
        site: 'LoicSapone'
language: en
languages:
    -   code: en
        name: English
        locale: en_US
image: og.png
