title: 'Loïc Sapone'
baseline: 'Développeur web'
baseurl: 'https://localhost:8080/'
description: 'Loïc Sapone, développeur web basé à Grenoble - associé chez Mezcalito, compétant en backend et devops'
author:
    name: 'Loïc Sapone'
    url: 'https://loic-sapone.fr'
image: cecil-card.png
