name: Build and deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  extensions: mbstring, gd, imagick, intl, gettext

            - name: Checkout source
              uses: actions/checkout@v2

            - name: Build site
              env:
                  CECIL_BASEURL: ${{ secrets.CECIL_BASEURL }}
              uses: Cecilapp/Cecil-Action@v3

            - name: Deploy site to GitHub Pages
              uses: Cecilapp/GitHub-Pages-deploy@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  email: loic@sapone.fr
                  build_dir: _site
                  branch: site
                  cname: loic-sapone.fr